name: ci

on:
  push:
    branches: [ "" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "用于手动触发测试"
        required: true
        default: "v0.0.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Go 环境
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: 安装xgo以及upx
      - name: Install xgo
        run: |
          go install src.techknowlogick.com/xgo@latest
          sudo apt update
          sudo apt install upx  

      # Step 4: 编译项目
      - name: Cross-Compile using xgo
        run: |
          mkdir -p output
          xgo --targets=darwin/*,linux/*,windows/* \
          -out output/ncmctl ./cmd/ncmctl/main.go
          ls ./output

      # Step 5: 压缩文件
      - name: Compress and upload binaries
        run: |
          cp LICENSE output/LICENSE
          
          for file in output/*; do
            filename=$(basename "$file")
            ext="${filename##*.}"

            if [[ "$ext" == "exe" ]]; then
              new_name="ncmctl.exe"
            else
              new_name="ncmctl"
            fi

            mv "$file" "output/$new_name"
            
            # 使用 UPX 压缩文件
            upx --best "output/$new_name"
            
            # 验证压缩后的文件是否可执行
            if [[ "$ext" == "exe" ]]; then
              file "output/$new_name" | grep -q "PE32"
            else
              file "output/$new_name" | grep -q "ELF"
            fi
            if [[ $? -ne 0 ]]; then
              echo "ERROR: Compressed file $new_name is not valid!"
              exit 1
            fi
          
            sha256_file="output/${new_name}.sha256"
            sha256sum "output/$new_name" > "$sha256_file"

            tarball="output/${filename}.tar.gz"
            tar -czf "$tarball" -C output "$new_name" -C output "${new_name}.sha256" -C output LICENSE
          
            rm -f "output/$new_name" "output/${new_name}.sha256"
          done
          
          rm -f output/LICENSE

      # Step 6: 上传压缩包
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./output
          if-no-files-found: error

      # Step 7: 下载压缩包
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts*
          path: ./output
          merge-multiple: true

      # Step 8: 输出当前ref和生成的文件列表
      - name: Debug Release
        run: |
          echo "Current ref: ${{ github.ref }}"
          echo "Generated artifacts:"
          ls ./output
    

      # Step 9: 发布
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(inputs.tag, 'v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./output/*
          generate_release_notes: false
          fail_on_unmatched_files: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
