name: ci

on:
  push:
    branches: [ "" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Go 环境（可选，仅用于工具安装或调试）
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # 设置你的 Go 版本

      # Step 3: 拉取 xgo Docker 镜像并进行编译
      - name: Cross-compile with xgo
        run: |
          docker run --rm \
            -v "$(pwd)":/src \
            -v "$(pwd)/output":/output \
            ghcr.io/techknowlogick/xgo:latest \
            --targets=linux/amd64,windows/amd64,linux/arm64 \
            --out=/output/ncmctl \
            ./cmd/ncmctl/main.go

      # Step 4: 保存编译的二进制文件
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: output/
