name: ci

on:
  push:
    branches: [ "" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]
        include:
          - os: linux
            arch: amd64

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies for ${{ matrix.os }}
        run: |
          if [[ "${{ matrix.os }}" == "linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y clang brotli
          elif [[ "${{ matrix.os }}" == "windows" ]]; then
            choco install mingw -y
          elif [[ "${{ matrix.os }}" == "darwin" ]]; then
            brew install brotli
          fi

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=1 go build -o ncmctl-${{ matrix.os }}-${{ matrix.arch }} ./cmd/ncmctl/main.go
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            mv ncmctl-${{ matrix.os }}-${{ matrix.arch }} ncmctl-${{ matrix.os }}-${{ matrix.arch }}.exe
          fi
          echo "Build artifact generated: ncmctl-${{ matrix.os }}-${{ matrix.arch }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ncmctl-*
